language: python
env:
  - DEV=true
  - DEV=false
  global:
    - ANACONDA_USER=lightsource2
    # if ANACONDA_CHANNEL is not defined then the conda package will be
    # uploaded to the main channel.
    - ANACONDA_CHANNEL="development"
    - UPLOAD_ONLY_IF_BRANCH_IS="master"
    - secure: "URtCilMlIxGqUBaP4YHsLwBZO0ypNjl0g72dd7fXbPcJNhpHTEJy1K4MU7FP36ZCGx9RoRI60yjYVYmY/gp7Nw/SssZ75v1I+KMubtZ18LvRi9euurIPwxxsQAlY4ECn/baNgCl75zKFFtssUScuFX/i/zuPmkZMTBytXD6WMRc="

git:
  # hack around git fetch --unshallow failing and nuking the whole CI
  depth: 9999999

services:
  - mongodb

cache:
  directories:
    - $HOME/.cache/pip

python:
  - 2.7
  - 3.4
  - 3.5

before_install:
  # clone conda install/build/upload helper scripts and make them executable
  - git clone https://gist.github.com/613e015ad558b9149d33.git ~/scripts
  - chmod +x ~/scripts/*.sh
  # install miniconda/anaconda-client/conda-build
  - . ~/scripts/install-miniconda.sh
  - . ~/scripts/init-filestore.sh

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda update conda
  # install the dev packages of any of our dependencies
  - if [[ $DEV == 'true' ]]; then
      conda config --remove channels lightsource2;
      conda config --add channels lightsource2/channels/development;
    fi;
  # show the current state of the conda config.
  - conda info
  - conda create -n testenv pip nose python=$TRAVIS_PYTHON_VERSION pymongo six pyyaml numpy h5py jsonschema boltons doct
  - source activate testenv
  - conda install -c soft-matter pims
  - pip install coveralls
  - 'pip install https://github.com/NSLS-II/doct/zipball/master#egg=doct'
  - python setup.py install


script:
  - python run_tests.py
  # build the conda package on travis
  - if [[ $DEV == 'false' ]]; then
      . ~/scripts/conda-build.sh;
    fi;

after_success:
  - coveralls
  # upload the conda package to the $ANACONDA_CHANNEL in $ANACONDA_USER
  - if [[ $DEV == 'false' ]]; then
      . ~/scripts/anaconda-upload.sh;
    fi;


after_failure:
  - . ~/scripts/debug.sh
